--INSERT INTO ave (id, nome) VALUES (1000, 'Sabia');
--INSERT INTO ave (id, nome) VALUES (2000, 'Urubu');
--INSERT INTO ave (id, nome) VALUES (3000, 'Alma de Gato');
--INSERT INTO ave (id, nome) VALUES (4000, 'Carrapateiro');